styles/index.css
- 불필요한 /styles 삭제
<br/>
-
<br/>
=> [Remove] 불필요한 /styles 삭제

packages/user/README.md
<br/>
- README 내용을 수정했습니다.
- DemoLink 및 팀원 소개 추가
<br/>
<br/>
=> [Feature]: README 작성

packages/admin/components.json
<br/>
- shadcn path설정
<br/>
<br/>
=> [Feature] shadcn path설정

packages/admin/components.json, packages/admin/package.json, packages/admin/src/components/common/Alert.tsx, packages/admin/src/components/ui/alert-dialog.tsx, packages/admin/tsconfig.json, packages/user/components.json, packages/user/tsconfig.json, yarn.lock
- 어드민 페이지
<br/>
- 어드민 페이지에서 사용하는 alert dialog 생성
- dialog 바깥 부분 눌러도 닫히지 않음
<br/>
```ts
export default function Example() {
const handleAction = () => console.log('action');
return (
<Alert
showCancelButton={false}
openTrigger={<Button>열기</Button>}
actionTrigger={<Button onClick={handleAction}>확인</Button>}
>
내용입니다
</Alert>
);
}
```
<br/>
> 기획
=> [Feature][Task-52] 어드민 페이지에서 사용하는 alert dialog 생성

packages/user/src/styles/index.css, packages/user/tailwind.config.js
- 이벤트 페이지
<br/>
- font download (Hyundai Sans Head KR, Tenada)
- tailwind에 font 세팅
- 전역 스타일 세팅
<br/>
```tsx
/* Heading 1 ExtraBold */
<p className='text-heading-1 font-extrabold'>heading 1 extrabold</p>
<h1>heading 1 bold</p>
/* Body 1 Regular (default) */
<p className='body-1 font-regular'>body 1 normal</p>
<p>body 1 normal</p>
<div>body 1 normal</div>
```
<br/>
> 기획
=> [Feature][TASK-62] typography system

packages/user/components.json, packages/user/src/styles/index.css, packages/user/tailwind.config.js, packages/user/tailwind.config.ts, packages/user/tsconfig.json, yarn.lock
- 이벤트 페이지
<br/>
- color system 구현
- 기본 배경, 텍스트 색상 지정
<br/>
<br/>
=> [Feature][TASK-63] color system

packages/user/tailwind.config.ts
- 이벤트 페이지
<br/>
- tailwind theme spacing 
- tailwind 호환을 위해 피그마 내 토큰 값을 변경해 반영했습니다.
- 적용 시 100으로 나눈 값으로 생각해주시면 됩니다.
<br/>
```ts
const spacing = {
1: '2px',
2: '4px',
3: '8px',
4: '12px',
5: '16px',
6: '20px',
7: '24px',
8: '28px',
9: '32px',
10: '36px',
};
```
<br/>
=> [Feature][TASK-64] spacing

packages/user/src/components/popup/test/ShareButton.tsx, packages/user/src/types/user.d.ts
- 이벤트 페이지
<br/>
- 유형 검사 팝업 내 링크 공유 버튼
<br/>
<br/>
=> [Feature][Task-72] 유형 검사 팝업 내 링크 공유 버튼

packages/user/src/components/layout/BodyContainer.tsx, packages/user/src/components/layout/Footer.tsx, packages/user/src/components/layout/index.tsx, packages/user/src/components/layout/top/Banner.tsx, packages/user/src/components/layout/top/Header.tsx, packages/user/src/components/layout/top/TopSectionContainer.tsx, packages/user/src/constants/routePath.ts, packages/user/src/hooks/storage/index.ts, packages/user/src/hooks/storage/useUserStorage.ts, packages/user/src/hooks/useAuth.tsx, packages/user/src/routes/router.tsx, packages/user/tailwind.config.ts
- 이벤트 페이지
<br/>
- router 구현
- auth provider, hook 구현
- layout 구현: top section(header, banner), body, footer
=> [Feature][Task-76] 이벤트 웹페이지 라우터 및 레이아웃 구현

packages/admin/src/constants/routePath.ts, packages/admin/src/layouts/appLayout.tsx, packages/admin/src/libs/index.tsx, packages/admin/src/pages/start/LoginPage.tsx, packages/admin/src/routes/router.tsx
=> [Feature][Task-59] 어드민 로그인 페이지 퍼블리싱

packages/user/src/components/event/racing/timer/TimeUnit.tsx, packages/user/src/components/event/racing/timer/index.tsx, packages/user/src/hooks/query/useGetEventDuration.ts
- 이벤트 페이지
<br/>
- 이벤트 타이머 구현
- 렌더링 최소화되도록 React.memo 등을 적용해 구현했습니다. 
- 추후 flip animation 적용해보면 좋을 것 같습니다. 
<br/>
=> [Feature][Task-165] 이벤트 타이머 구현

packages/common/src/constants/api.ts, packages/common/src/utils/api/fetchInterceptors.ts, packages/common/src/utils/index.ts, packages/common/src/utils/storage/cookie/getCookie.ts, packages/common/src/utils/storage/cookie/index.ts, packages/common/src/utils/storage/cookie/setCookie.ts, packages/common/src/utils/storage/index.ts
- 이벤트 페이지
- 어드민 페이지
<br/>
- 쿠키 Getter, Setter 제작
- fetchInterceptor ACCESS_TOKEN 쿠키 주입 기능 추가
=> [Feature][Task-190]  setCookie, getCookie 추가 및 fetchInterceptor에 AccessToken 적용

packages/user/src/components/common/StepProgress.tsx, packages/user/src/components/shared/modal/teamSelectModal/quiz/index.tsx
- 이벤트 페이지
<br/>
> 왜인지 모르겠는데 git이 난리가 나있어서 감안하고 봐주시면 감사하겠습니다 ㅋㅋㅋㅋ
> 실질적으로 해당 PR과 관련된 내용은 StepProgress 하나일겁니다 ,, 
- 유형 검사 모달 퀴즈 리스트 퍼널 내부 step progress 구현
<br/>
<br/>
=> [Feature][Task-194] 유형 검사 모달 퀴즈 리스트 퍼널 내부 step progress 구현

packages/user/src/components/event/chatting/index.tsx, packages/user/src/services/socket/index.ts, packages/user/src/services/socket/socket.ts
- 이벤트 페이지
<br/>
- socket class를 공용으로 사용하기 위해 common package로 이동하는 과정에서 다음의 에러 발생
_-_ `Error: Dynamic require of "crypto" is not supported`
- browser / nodejs 환경 차이로 발생하는 오류로 예상했으나 아직 해결하지 못한 상태 
- 임시로 user package 내부에 동일한 class 중복 선언해 처리해둠
<br/>
<br/>
=> [Fix] 임시 해결 - Error: Dynamic require of "crypto" is not supported

packages/user/src/App.tsx, packages/user/src/components/common/toast/Toast.tsx, packages/user/src/components/event/chatting/index.tsx, packages/user/src/components/event/racing/controls/ChargeButtonContent.tsx, packages/user/src/components/event/racing/controls/ChargeButtonWrapper.tsx, packages/user/src/components/event/racing/controls/ControlButton.tsx, packages/user/src/components/event/racing/dashboard/index.tsx, packages/user/src/components/layout/ErrorBoundary.tsx, packages/user/src/components/layout/ErrorContainer.tsx, packages/user/src/components/layout/header/user/index.tsx, packages/user/src/components/shared/modal/teamSelectModal/ResultStep.tsx, packages/user/src/hooks/socket/useRacingSocket.ts, packages/user/src/pages/ErrorPage.tsx, packages/user/src/routes/router.tsx
- 이벤트 페이지
<br/>
- router 내 errorElement 추가
- global error boundary 추가
<br/>
<br/>
```ts
const routes: RouteObject[] = [
{
path: RoutePaths.Index,
element: (
<AuthProvider>
<Layout />
</AuthProvider>
),
errorElement: <ErrorPage />,
children: [
{
index: true,
element: <HomePage />,
},
{
path: RoutePaths.Event,
element: <EventPage />,
},
],
},
];
const router = createBrowserRouter(routes);
export default router;
```
```ts
export default function App() {
useCursor();
return (
<>
<AppProviders>
<GlobalErrorBoundary>
<RouterProvider router={router} fallbackElement={<>loading...</>} />
</GlobalErrorBoundary>
<ToasterStack />
</AppProviders>
<CasperCursor />
</>
);
}
```
=> [Feature][Task-185] Global Error Boundary 추가

packages/user/src/components/layout/ErrorContainer.tsx, packages/user/src/pages/ErrorPage.tsx, packages/user/src/pages/NotFoundErrorPage.tsx, packages/user/src/routes/router.tsx
- 이벤트 페이지
<br/>
- #61 에서 구현한 error page 컴포넌트 활용해 404 not found error page 구현
<br/>
<br/>
=> [Feature][Task-184] 404 not found error page 구현

packages/user/src/hooks/socket/useChatSocket.ts
- 이벤트 페이지
<br/>
- 서버에 chat team 잘못 보내주는 문제 수정
<br/>
<br/>
=> [Fix] 서버에 chat team 잘못 보내주는 문제 수정

packages/user/src/components/shared/ShareCountTeamCard.tsx, packages/user/src/hooks/query/useGetLinkShareCount.ts
- 이벤트 페이지
<br/>
- GET 공유 링크 클릭 수 api 연동
<br/>
=> [Feature][Task-209] GET 공유 링크 클릭 수 api 연동

packages/user/src/components/event/racing/controls/Gauge.tsx, packages/user/src/components/event/racing/dashboard/Casper.tsx, packages/user/src/components/event/racing/index.tsx, packages/user/src/services/socket.ts, packages/user/src/styles/theme/animations.ts
- 이벤트 페이지
<br/>
> @jun-ha 님 요청으로 진행. 내일 QA 후 추가 보완 예정
애니메이션 .. 어렵네요 .... 
- 레이싱 게임 캐스퍼 및 게이지 애니메이션 보완
<br/>
<br/>
=> [Feature][Task-246] 레이싱 게임 캐스퍼 및 게이지 애니메이션 보완

packages/admin/index.html, packages/admin/src/components/appLayout/Header.tsx, packages/admin/src/components/appLayout/SideBar.tsx, packages/admin/src/components/appLayout/SideBarContainer.tsx, packages/admin/src/components/chat/Chat.tsx, packages/admin/src/components/chat/RealTimeChatting.tsx, packages/admin/src/components/common/Tab.tsx, packages/admin/src/components/table/ResultTable.tsx, packages/admin/src/constants/api.ts, packages/admin/src/constants/environments.ts, packages/admin/src/hooks/socket/index.ts, packages/admin/src/hooks/socket/useChatSocket.ts, packages/admin/src/hooks/useEvent.tsx, packages/admin/src/layouts/appLayout.tsx, packages/admin/src/pages/events/CommonEventTab.tsx, packages/admin/src/pages/events/RaceEventTab.tsx, packages/admin/src/pages/review/Review.tsx, packages/admin/src/pages/start/LoginPage.tsx, packages/admin/src/pages/winner/WinnerResult.tsx, packages/admin/src/services/api/types/apiType.ts, packages/admin/src/services/socket.ts, packages/admin/src/types/racing.d.ts, packages/admin/vite.config.ts, packages/common/src/utils/api/index.ts, packages/common/src/utils/storage/cookie/getCookie.ts, packages/user/src/components/shared/timer/TimeUnit.tsx, packages/user/src/main.tsx, packages/user/src/pages/NotStartedEventPage.tsx, packages/user/src/styles/theme/animations.ts
- 이벤트 페이지
- 어드민 페이지
<br/>
- 어드민 페이지: Socket연동
- 어드민 페이지: Chatting 연동
- 공통:  FetchWrapper Text 데이터 핸들링 -> code 상관없이 Text로 들어오면 message에 Text 담기게 수정
- 이벤트 페이지: 시계 플립 기능 수정중
<br/>
=> [Feature][Task-171] 어드민 페이지 Socket연동 및 에러 핸들링 추기

packages/admin/src/components/chat/RealTimeChatting.tsx, packages/user/src/pages/NotStartedEventPage.tsx
- 이벤트 페이지
- 어드민 페이지
<br/>
- 빌드 오류 수정
<br/>
=> [Fix] build error

packages/user/src/App.tsx, packages/user/src/hooks/query/useGetUserInfo.ts, packages/user/src/routes/loader/index.ts
- 이벤트 페이지
<br/>
- 유저 정보 prefetch 
- Global Loading component
<br/>
=> [Feature] 유저 정보 prefetch (react-router-dom loader)

.github/workflows/deploy.yml, packages/admin/src/services/api/types/apiType.ts
- 어드민 페이지
<br/>
- main merge 누락된거 추가
=> [Feature][Task-171] CDN방식 추가

packages/admin/src/components/chat/Chat.tsx, packages/admin/src/components/chat/RealTimeChatting.tsx, packages/admin/src/hooks/socket/index.ts, packages/admin/src/hooks/socket/useChatSocket.ts, packages/admin/src/services/socket.ts, packages/common/src/components/chat/Message.tsx, packages/common/src/constants/socket.ts, packages/user/src/components/shared/modal/teamSelectModal/index.tsx, packages/user/src/hooks/socket/index.ts, packages/user/src/hooks/socket/useChatSocket.ts, packages/user/src/services/socket.ts
- 이벤트 페이지
- 어드민 페이지
<br/>
- User
- Block 소켓 이벤트 수신 적용
- Admin
- Block 소켓 이벤트 송수신 적용
- Notice 소켓 이벤트 송수신 적용
=> [Feature][Task-42]  Socket연결 (Block, Notice)

packages/common/src/components/chat/Message.tsx
- 공통 패키지
<br/>
- 유형 검사 없는 메시지에도 색상 지정
<br/>
<br/>
=> [Feature][Task-279] 유형 검사 없는 메시지에도 색상 지정

packages/admin/src/components/appLayout/SideBarContainer.tsx, packages/admin/src/components/chat/Chat.tsx, packages/admin/src/components/common/Tab.tsx, packages/admin/src/components/table/ResultTable.tsx, packages/admin/src/layouts/appLayout.tsx, packages/admin/src/pages/events/CommonEventTab.tsx, packages/admin/src/pages/events/RaceEventTab.tsx, packages/common/src/components/chat/Message.tsx, packages/common/src/utils/socket.ts, packages/user/src/components/common/PendingContainer.tsx, packages/user/src/components/event/chatting/index.tsx, packages/user/src/components/event/racing/dashboard/card/UnassignedCard.tsx, packages/user/src/components/event/racing/dashboard/card/index.tsx, packages/user/src/components/event/racing/dashboard/chargeButton.tsx, packages/user/src/components/event/racing/index.tsx, packages/user/src/components/home/eventHero/racing/Cars.tsx, packages/user/src/components/home/eventHero/racing/Caspers.tsx, packages/user/src/components/home/eventHero/racing/Effects.tsx, packages/user/src/components/home/quizHint/HintCards.tsx, packages/user/src/components/home/teamsDescriptions/index.tsx, packages/user/src/components/layout/header/tab/index.tsx, packages/user/src/components/shared/modal/fcfs/QuizStep.tsx, packages/user/src/components/shared/modal/fcfs/index.tsx, packages/user/src/components/shared/withAuthHOC.tsx, packages/user/src/hooks/query/useSubmitFCFSQuiz.ts, packages/user/src/hooks/socket/useChatSocket.ts, packages/user/src/main.tsx, packages/user/src/pages/NotStartedEventPage.tsx, packages/user/src/services/socket.ts
- 이벤트 페이지
<br/>
- modal component lazy loading 처리
- fix: 선착순 퀴즈 채점 결과 화면 보이지 않았던 문제 해결
- fix: 채팅 상단 포커싱
- design: 유형 검사 미진행 유저인 경우 채팅 gray color 표기
- feat: 이벤트 진행 시작될 때 자동 새로 고침
- design: 레이싱 게임 버튼 디자인 수정
<br/>
> 레이싱 게임 버튼 디자인 수정
ㄴ hover, active
> 유형 검사 미진행 유저인 경우 채팅 gray color 표기
=> [QA] 최종 QA 피드백 반영

packages/common/src/components/chat/Message.tsx, packages/common/src/components/chat/index.ts, packages/user/src/components/event/chatting/index.tsx, packages/user/src/components/event/racing/dashboard/chargeButton.tsx, packages/user/src/components/event/racing/index.tsx, packages/user/src/constants/storageKey.ts, packages/user/src/hooks/socket/useChatSocket.ts, packages/user/src/hooks/storage/useNoticeStorage.ts, packages/user/src/pages/NotStartedEventPage.tsx
- 이벤트 페이지
<br/>
- 실시간 기대평 기능에 공지사항 받아오기 기능 추가
<br/>
=> [Feature] 실시간 기대평 기능에 공지사항 받아오기 기능 추가

packages/admin/src/components/chat/Chat.tsx, packages/admin/src/components/chat/RealTimeChatting.tsx, packages/admin/src/components/error/CommonErrorBoundary.tsx, packages/admin/src/hooks/socket/useChatSocket.ts, packages/admin/src/hooks/useEvent.tsx, packages/admin/src/layouts/appLayout.tsx, packages/admin/src/libs/index.tsx, packages/admin/src/pages/winner/WinnerResult.tsx, packages/admin/src/services/socket.ts, packages/common/src/constants/socket.ts, packages/user/src/services/socket.ts
- 어드민 페이지
<br/>
- QA 수정
- Socket 연결( Notice History추가 )
=> [Feature][Task-42]  8.21일 QA 수정

packages/user/package.json, packages/user/vite.config.ts, yarn.lock
- 이벤트 페이지
<br/>
- 이미지 압축
- 코드 스플릿
- 빌드 압축 성능 향상
<br/>
```bash
vite v5.4.1 building for production...
✓ 314 modules transformed.
dist/index.html                                 1.72 kB │ gzip:   0.79 kB
dist/assets/index-CzuN246i.css                 55.54 kB │ gzip:   9.82 kB
dist/assets/NotFoundErrorPage-DbVc-N_u.js       0.16 kB │ gzip:   0.18 kB
dist/assets/TriggerButtonWrapper-BXmc9J3L.js    0.16 kB │ gzip:   0.15 kB
dist/assets/ErrorPage-MoPthZOm.js               0.23 kB │ gzip:   0.23 kB
dist/assets/scrollToElementId-DDPST3ho.js       0.28 kB │ gzip:   0.23 kB
dist/assets/index-C4cIGDSy.js                   0.34 kB │ gzip:   0.26 kB
dist/assets/Chip-CI4GOUNE.js                    0.37 kB │ gzip:   0.26 kB
dist/assets/externalLinks-BosX4DBT.js           0.39 kB │ gzip:   0.23 kB …
```
=> [Perf] 빌드 용량 축소 & 이미지 압축

packages/user/public/Google Search Console Verification.html
- 이벤트 페이지
<br/>
- Google SEO 파일 추가
<br/>
=> [Perf] Google SEO
